### ISSUE TITLE
mandoc step fails on OpenBSD

### ISSUE THREAD

**Issue by mlarkin2015** [xcllnt/openiked#6]
Mandoc step fails on OpenBSD-current:

sed: 0: ./iked.0: No such file or directory
**\* Error 1 in iked (Makefile:1092 'iked.8.out')
**\* Error 1 in iked (Makefile:1015 'install-exec-am')
**\* Error 1 in iked (Makefile:958 'install-am')

Apparently this comes from:

manpage=./`echo iked.8.out | sed 's/\.[1-9]\.out$/\.0/'`

unsure how it ended up thinking that it needed a '0' on the end there. Looks like some autoconf goo did that?

**Comment by mlarkin2015** [comment]
This also happens on iked.conf.5 and ikectl.8

**Comment by xcllnt** [comment]
Fixed
